import { Inter } from "@next/font/google";
import Head from "next/head";
import { useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const count = useSelector((state) => state.countSliceReducer.count);
  console.log("🚀 ~ file: index.js:11 ~ Home ~ count", count);
  return (
    <>
      <Head>
        <title>NEXT BOILERPLATE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>home</div>
    </>
  );
}
